### ISSUE TITLE
Loc: Fix Odometry Kinematic Parameters and Other Issues with Odometry

### ISSUE THREAD

**Issue by Ikemura-kei** [Ikemura-kei/DD2419-Team-2#7]
The current implementation of odometry is a bit wrong as having inaccurate kinematic parameters. Also the time interval between updates is fixed, where it should be dynamic actually. So we will address these problems in this issue.

**DoD**
- [x] Fix odometry parameters to the correct ones
- [x] Use dynamic time interval (dt)
- [x] Be able to have the laser scans NOT moving (almost) in rviz under odom frame.

**Comment by jordanbierbrier** [comment]
Thanks for linking the issue!
