### ISSUE TITLE
Sim: Ground Truth Data Publication

### ISSUE THREAD

**Issue by Ikemura-kei** [Ikemura-kei/DD2419-Team-2#9]
To facilitate isoltaed module development, we need to prepare ground truth data to replace dependent modules. For example, a navigation system requires localization output, while before having a good implementation of the localization part, we can just use the ground truth position of the robot to develop the navigation system. Same goes for other module development. 

**DoD**
In this update, we will include the following ground truth data:
- [x] Ground truth robot pose, published as odom->base_link transformation
- [x] Map as 2D occupancy grid

**Comment by kevingao1113** [comment]
I created a new issue about the 2nd DoD Publishing Ground truth of object positions (#12 )and uploaded my code to corresponding branch. I'll update my progress there these days, Looking forward to provide suggestions and requests about it.

**Comment by Ikemura-kei** [comment]
I think there are some misunderstandings. All of the stuff here is only concerned with the simulator, actually you don't need to do anything about thr 2nd DoD, its just simulating the position of the objects.

**Comment by Ikemura-kei** [comment]
But yea the new issue about perception is still valid, thanks.

**Comment by kevingao1113** [comment]
> I think there are some misunderstandings. All of the stuff here is only concerned with the simulator, actually you don't need to do anything about thr 2nd DoD, its just simulating the position of the objects.

Oh haha, I misunderstood it. I thought the ground truth you mentioned was something like the estimated object position I'm trying to do in the object detector. I confused them.
